language: python
python:
  - "3.8"

before_install:
  - pip install pycodestyle

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pytest -m pytest tests/
  - coverage run --source="src/" -m pytest
  - pycodestyle src/ --ignore=E722,E501,E402
